---
# Deployment of app-test
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-test
  template:
    metadata:
      labels:
        app: app-test
    spec:
      containers:
      - name: app-test
        image: ghcr.io/ryanob/app-test:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
 name: front-service
spec:
 type: LoadBalancer
 ports:
 - port: 3000
 selector:
  app: app-test
      